version: "2.1"

services:
  mysql:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: jp.mysql
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: "jp"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "0000"
    image: mysql:5.6
    ports:
      - "5000:3306"
