# Generated by Django 2.2.4 on 2019-12-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=3000)),
                ('regist_date', models.DateTimeField()),
                ('delete_data', models.DateTimeField()),
                ('delete_yn', models.CharField(default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanja', models.CharField(max_length=255)),
                ('hiragana', models.CharField(max_length=255)),
                ('hangul', models.CharField(max_length=255)),
                ('regist_date', models.DateTimeField()),
                ('delete_data', models.DateTimeField()),
                ('delete_yn', models.CharField(default='N', max_length=1)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
        ),
    ]
