# Generated by Django 3.0.1 on 2019-12-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20191226_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postinfo',
            old_name='post_id',
            new_name='post',
        ),
    ]
