# Generated by Django 3.0.1 on 2019-12-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20191226_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='regist_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postinfo',
            name='regist_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
